[project]
name = "ics-filter-prototyping"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.4",
    "ics>=0.7.2",
    "requests>=2.32.3",
]
