CREATE TABLE filtered_calendars (
    id INTEGER NOT NULL PRIMARY KEY,
    filter_id INTEGER NOT NULL,
    calendar_id INTEGER NOT NULL,

    name TEXT NOT NULL,
    color TEXT NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (filter_id) REFERENCES filters(id) ON DELETE CASCADE,
    FOREIGN KEY (calendar_id) REFERENCES calendars(id) ON DELETE CASCADE
);
