CREATE TABLE IF NOT EXISTS filters (
    id INTEGER NOT NULL PRIMARY KEY,
    filter_type TEXT NOT NULL,
    name TEXT NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
